title: "Kai-Hua (Kelvin) Wang"
description: "M.S. in Mechanical Engineering @ Carnegie Mellon"
url: https://kelvin1106.github.io
baseurl: ""

author:
  location: "Pittsburgh, PA"
  employer: "Carnegie Mellon University"
  email: "kaihuaw@andrew.cmu.edu"
  github: "Kelvin1106"
  linkedin: "https://www.linkedin.com/in/kaihuawang/"
